site_name: helix-new
site_url: https://helix-text.github.io
nav:
    - Home: index.md
    - Errors: errors.md
    - Rest Api: rest-api.md
    - Websocket Api: web-socket-api.md

theme:
    name: readthedocs    
